from chatbot.models import Question

questions = [
    'Where is the college located?',
    'How far is the college from Andheri Railway station?',
    'Which is the nearest Railway station?',
    'How far is the college from Andheri metro station?',
    'Which is the nearest metro station?',
    'How far is the college from the bus stop?',
    'Which is the nearest bus stop?',
    'Where is the college canteen located?',
    'Where is the college library located?',
    'Where is the main office of the college?',
    'Where is the sports room of the college?',
    'Where is the staff room of the Computer Science department?',
    'Where is the staff room of the Information Technology department?',
    'Where is the staff room of the Biotechnology department?',
    'Where is the staff room of the BAMMC department?',
    'Where is the principal office located?',
    'Where is the director office located?',
    'Where is the enquiry counter of the college?',
    'Where is the fees counter of the college?',
    'Where is the college gym located?',
    'Where is the college ground located?',
    'Where is the IT lab of the college?',
    'Where is the CS lab of the college?',
    'Where is the Biotech lab of the college?',
    'Where is the auditorium of the college?',
    'Where is the classroom of the Computer Science department?',
    'Where is the classroom of the Information Technology department?',
    'Where is the classroom of the Biotechnology department?',
    'Where is the classroom of the BAMMC department?',
    'Where is the AC classroom of the Computer Science department?',
    'Where is the AC classroom of the Information Technology department?',
    'Where is the boys washroom in the college?',
    'Where is the girls washroom in the college?',
    'Where is the washroom in the college?',
    'Where is the carrom room in college?',
    'Where is the tennis court in college?',
    'Where is the football ground in college?',
    'Where is the cricket ground in college?',
    'Where is the flagpost in college?',
    'Where is the parking available for college students?',
    'Where is the parking available for college staff?',
    'Where is the watchman cabin of the college?',
    'Where is the staircase in the college?',
    'Where is the cultural room of the college?',
    'Where is the place to sit in college campus?',
    'Where is the CCSP classroom in the college?',
    'Where is the CCSP lab in the college?',
    'Where is the CCSP office in the college?',
]

for question in questions:
    Question.objects.create(text=question)