from chatbot.models import Question, Category

questions = [
    'where is college located',
    'how far college is from andheri Railway station',
    'which is the nearest Railway station',
    'how far college is from andheri metro station',
    'which is the nearest metro station',
    'How far college is from bust stop',
    'which is the nearest bus stop',
    'where is the college canteen located',
    'where is the college library located',
    'where is the main office of the college',
    'where is the sports room of the college',
    'where is the staff room of computer science department',
    'where is the staff room of Information Technology department',
    'where is the staff room of Biotechnology department',
    'where is the staff room of BAMMC department',
    'where is the principal office located',
    'where is the director office located',
    'where is the enquiry counter of the college',
    'where is the fees counter of the college',
    'where is the college gym located',
    'where is the college ground located',
    'where is the IT lab of the college',
    'where is the CS lab of the college',
    'where is the Biotech lab of the college',
    'where is the auditorium of the college',
    'where is the class room of cs depertment',
    'where is the class room of IT dapartment',
    'where is the class room of biotech dapartment',
    'where is the class room of the BAMMC department',
    'where is the Ac classroom of cs department',
    'where is the Ac classroom of the IT department',
    'where is boys washroom in the college',
    'where is girls washroom in the college',
    'where is washroom in the college',
    'where is carrom room in college',
    'where is tennis court in college',
    'where is football ground in college',
    'where is cricket ground in college',
    'where is flagpost in college',
    'where is the parking available for college student',
    'where is the parking available for college staff',
    'where is the watchman cabin of the college',
    'where is the staircase in the college',
    'where is the cultural room of the college',
    'where is the place to sit in college campus',
    'where is the ccsp classroom in the college ',
    'where is the ccsp lab in the college',
    'where is the ccsp office in the college'
]

for question in questions:
    category = Category.objects.create(name='locations')
    Question.objects.create(text=question, category=category)